interface ZIF_BOB
  public .


  interfaces /BOBF/IF_LIB_CONSTANTS .

  constants:
    BEGIN OF SC_ACTION,
      BEGIN OF ITEM,
 CREATE_ITEM                    TYPE /BOBF/ACT_KEY VALUE '000C29858D4A1EE5B6DB9C665FDE365B',
 DELETE_ITEM                    TYPE /BOBF/ACT_KEY VALUE '000C29858D4A1EE5B6DB9C665FDEB65B',
 SAVE_ITEM                      TYPE /BOBF/ACT_KEY VALUE '000C29858D4A1EE5B6DB9C665FDF365B',
 UPDATE_ITEM                    TYPE /BOBF/ACT_KEY VALUE '000C29858D4A1EE5B6DB9C665FDE765B',
 VALIDATE_ITEM                  TYPE /BOBF/ACT_KEY VALUE '000C29858D4A1EE5B6DB9C665FDEF65B',
      END OF ITEM,
      BEGIN OF ROOT,
 CREATE_ROOT                    TYPE /BOBF/ACT_KEY VALUE '000C292422631ED5B4AE6B6B4AC1150D',
 DELETE_ROOT                    TYPE /BOBF/ACT_KEY VALUE '000C292422631ED5B4AE6B6B4AC1950D',
 LOCK_ROOT                      TYPE /BOBF/ACT_KEY VALUE '000C292422631ED5B4AE6B6B4AC0550D',
 SAVE_ROOT                      TYPE /BOBF/ACT_KEY VALUE '000C292422631ED5B4AE6B6B4AC2150D',
 UNLOCK_ROOT                    TYPE /BOBF/ACT_KEY VALUE '000C292422631ED5B4AE6B6B4AC0950D',
 UPDATE_ROOT                    TYPE /BOBF/ACT_KEY VALUE '000C292422631ED5B4AE6B6B4AC1550D',
 VALIDATE_ROOT                  TYPE /BOBF/ACT_KEY VALUE '000C292422631ED5B4AE6B6B4AC1D50D',
      END OF ROOT,
    END OF SC_ACTION .
  constants:
    BEGIN OF SC_ACTION_ATTRIBUTE,
      BEGIN OF ROOT,
        BEGIN OF LOCK_ROOT,
 GENERIC                        TYPE STRING VALUE 'GENERIC',
 EDIT_MODE                      TYPE STRING VALUE 'EDIT_MODE',
 ALL_NONE                       TYPE STRING VALUE 'ALL_NONE',
 SCOPE                          TYPE STRING VALUE 'SCOPE',
 FORCE_INVALIDATION             TYPE STRING VALUE 'FORCE_INVALIDATION',
        END OF LOCK_ROOT,
        BEGIN OF UNLOCK_ROOT,
 GENERIC                        TYPE STRING VALUE 'GENERIC',
 EDIT_MODE                      TYPE STRING VALUE 'EDIT_MODE',
 ALL_NONE                       TYPE STRING VALUE 'ALL_NONE',
 SCOPE                          TYPE STRING VALUE 'SCOPE',
 FORCE_INVALIDATION             TYPE STRING VALUE 'FORCE_INVALIDATION',
        END OF UNLOCK_ROOT,
      END OF ROOT,
    END OF SC_ACTION_ATTRIBUTE .
  constants:
    BEGIN OF SC_ALTERNATIVE_KEY,
      BEGIN OF ROOT,
 ALICE_KEY                      TYPE /BOBF/OBM_ALTKEY_KEY VALUE '000C292422631ED5B4AE7359E632750E',
      END OF ROOT,
    END OF SC_ALTERNATIVE_KEY .
  constants:
    BEGIN OF SC_ASSOCIATION,
      BEGIN OF ITEM,
 MESSAGE                        TYPE /BOBF/OBM_ASSOC_KEY VALUE '000C29858D4A1EE5B6DB9C665FDDD65B',
 PROPERTY                       TYPE /BOBF/OBM_ASSOC_KEY VALUE '000C29858D4A1EE5B6DB9C665FDE165B',
 TO_PARENT                      TYPE /BOBF/OBM_ASSOC_KEY VALUE '000C29858D4A1EE5B6DB9AA3BDE77658',
 TO_ROOT                        TYPE /BOBF/OBM_ASSOC_KEY VALUE '000C29858D4A1EE5B6DB9AA3BDE79658',
      END OF ITEM,
      BEGIN OF ITEM_MESSAGE,
 TO_PARENT                      TYPE /BOBF/OBM_ASSOC_KEY VALUE '000C29858D4A1EE5B6DB9C665FDF765B',
      END OF ITEM_MESSAGE,
      BEGIN OF ITEM_PROPERTY,
 TO_PARENT                      TYPE /BOBF/OBM_ASSOC_KEY VALUE '000C29858D4A1EE5B6DB9C665FDF965B',
      END OF ITEM_PROPERTY,
      BEGIN OF ROOT,
 ITEM                           TYPE /BOBF/OBM_ASSOC_KEY VALUE '000C29858D4A1EE5B6DB9AA3BDE73658',
 LOCK                           TYPE /BOBF/OBM_ASSOC_KEY VALUE '000C292422631ED5B4AE6B6B4AC0350D',
 MESSAGE                        TYPE /BOBF/OBM_ASSOC_KEY VALUE '000C292422631ED5B4AE6B6B4ABFF50D',
 PROPERTY                       TYPE /BOBF/OBM_ASSOC_KEY VALUE '000C292422631ED5B4AE6B6B4AC0F50D',
      END OF ROOT,
      BEGIN OF ROOT_LOCK,
 TO_PARENT                      TYPE /BOBF/OBM_ASSOC_KEY VALUE '000C292422631ED5B4AE6B6B4AC2750D',
      END OF ROOT_LOCK,
      BEGIN OF ROOT_MESSAGE,
 TO_PARENT                      TYPE /BOBF/OBM_ASSOC_KEY VALUE '000C292422631ED5B4AE6B6B4AC2550D',
      END OF ROOT_MESSAGE,
      BEGIN OF ROOT_PROPERTY,
 TO_PARENT                      TYPE /BOBF/OBM_ASSOC_KEY VALUE '000C292422631ED5B4AE6B6B4AC2950D',
      END OF ROOT_PROPERTY,
    END OF SC_ASSOCIATION .
  constants:
    BEGIN OF SC_ASSOCIATION_ATTRIBUTE,
      BEGIN OF ITEM,
        BEGIN OF PROPERTY,
 ALL_NODE_PROPERTY              TYPE STRING VALUE 'ALL_NODE_PROPERTY',
 ALL_NODE_ATTRIBUTE_PROPERTY    TYPE STRING VALUE 'ALL_NODE_ATTRIBUTE_PROPERTY',
 ALL_ASSOCIATION_PROPERTY       TYPE STRING VALUE 'ALL_ASSOCIATION_PROPERTY',
 ALL_ASSOCIATION_ATTRIBUTE_PROP TYPE STRING VALUE 'ALL_ASSOCIATION_ATTRIBUTE_PROP',
 ALL_ACTION_PROPERTY            TYPE STRING VALUE 'ALL_ACTION_PROPERTY',
 ALL_ACTION_ATTRIBUTE_PROPERTY  TYPE STRING VALUE 'ALL_ACTION_ATTRIBUTE_PROPERTY',
 ALL_QUERY_PROPERTY             TYPE STRING VALUE 'ALL_QUERY_PROPERTY',
 ALL_QUERY_ATTRIBUTE_PROPERTY   TYPE STRING VALUE 'ALL_QUERY_ATTRIBUTE_PROPERTY',
 ALL_SUBTREE_PROPERTY           TYPE STRING VALUE 'ALL_SUBTREE_PROPERTY',
        END OF PROPERTY,
      END OF ITEM,
      BEGIN OF ROOT,
        BEGIN OF PROPERTY,
 ALL_NODE_PROPERTY              TYPE STRING VALUE 'ALL_NODE_PROPERTY',
 ALL_NODE_ATTRIBUTE_PROPERTY    TYPE STRING VALUE 'ALL_NODE_ATTRIBUTE_PROPERTY',
 ALL_ASSOCIATION_PROPERTY       TYPE STRING VALUE 'ALL_ASSOCIATION_PROPERTY',
 ALL_ASSOCIATION_ATTRIBUTE_PROP TYPE STRING VALUE 'ALL_ASSOCIATION_ATTRIBUTE_PROP',
 ALL_ACTION_PROPERTY            TYPE STRING VALUE 'ALL_ACTION_PROPERTY',
 ALL_ACTION_ATTRIBUTE_PROPERTY  TYPE STRING VALUE 'ALL_ACTION_ATTRIBUTE_PROPERTY',
 ALL_QUERY_PROPERTY             TYPE STRING VALUE 'ALL_QUERY_PROPERTY',
 ALL_QUERY_ATTRIBUTE_PROPERTY   TYPE STRING VALUE 'ALL_QUERY_ATTRIBUTE_PROPERTY',
 ALL_SUBTREE_PROPERTY           TYPE STRING VALUE 'ALL_SUBTREE_PROPERTY',
        END OF PROPERTY,
      END OF ROOT,
    END OF SC_ASSOCIATION_ATTRIBUTE .
  constants:
    SC_BO_KEY  TYPE /BOBF/OBM_BO_KEY VALUE '000C292422631ED5B4AE6B6B4ABF550D' .
  constants:
    SC_BO_NAME TYPE /BOBF/OBM_NAME VALUE 'ZBOB' .
  constants:
    SC_MODEL_VERSION TYPE /BOBF/CONF_VERSION VALUE '00000' .
  constants:
    BEGIN OF SC_NODE,
 ITEM                           TYPE /BOBF/OBM_NODE_KEY VALUE '000C29858D4A1EE5B6DB9AA3BDE71658',
 ITEM_MESSAGE                   TYPE /BOBF/OBM_NODE_KEY VALUE '000C29858D4A1EE5B6DB9C665FDDB65B',
 ITEM_PROPERTY                  TYPE /BOBF/OBM_NODE_KEY VALUE '000C29858D4A1EE5B6DB9C665FDDF65B',
 ROOT                           TYPE /BOBF/OBM_NODE_KEY VALUE '000C292422631ED5B4AE6B6B4ABF950D',
 ROOT_LOCK                      TYPE /BOBF/OBM_NODE_KEY VALUE '000C292422631ED5B4AE6B6B4AC0150D',
 ROOT_MESSAGE                   TYPE /BOBF/OBM_NODE_KEY VALUE '000C292422631ED5B4AE6B6B4ABFD50D',
 ROOT_PROPERTY                  TYPE /BOBF/OBM_NODE_KEY VALUE '000C292422631ED5B4AE6B6B4AC0D50D',
    END OF SC_NODE .
  constants:
    BEGIN OF SC_NODE_ATTRIBUTE,
      BEGIN OF ITEM,
  NODE_DATA                      TYPE STRING VALUE 'NODE_DATA',
  INT_NUMBER                     TYPE STRING VALUE 'INT_NUMBER',
      END OF ITEM,
      BEGIN OF ROOT,
  NODE_DATA                      TYPE STRING VALUE 'NODE_DATA',
  ALICE_KEY                      TYPE STRING VALUE 'ALICE_KEY',
      END OF ROOT,
    END OF SC_NODE_ATTRIBUTE .
  constants:
    BEGIN OF SC_NODE_CATEGORY,
      BEGIN OF ITEM,
 ITEM                           TYPE /BOBF/OBM_NODE_CAT_KEY VALUE '000C29858D4A1EE5B6DB9C665FDD965B',
      END OF ITEM,
      BEGIN OF ROOT,
 ROOT                           TYPE /BOBF/OBM_NODE_CAT_KEY VALUE '000C292422631ED5B4AE6B6B4ABFB50D',
      END OF ROOT,
    END OF SC_NODE_CATEGORY .
endinterface.